#!/bin/bash
#!/bin/bash

#PBS -l select=1:ncpus=12:ngpus=1:mem=16gb
#PBS -l walltime=1:00:00
#PBS -M z5208494@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5208494/OutputReport

# Go into thesis folder
cd /home/z5208494/thesis/

echo ""$(date)"" 2>&1 | tee -a output/outputunfreeznumwrk2cpu12g1.txt

# This runs the test script
python3 run_basic_unfreeze.py 2>&1 | tee -a output/outputunfreeznumwrk2cpu12g1.txt
