#!/bin/bash
#!/bin/bash

#PBS -l select=1:ncpus=24:ngpus=3:mem=138gb
#PBS -l walltime=12:00:00
#PBS -M z5208494@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5208494/OutputReport

# Go into thesis folder
cd /home/z5208494/thesis/

echo ""$(date)"" 2>&1 | tee -a output/out_xlsr_unfreeze_step25.txt

# This runs the test script
python3 run_xlsr_unfreezestep25.py 2>&1 | tee -a output/out_xlsr_unfreeze_step25.txt
